name: Production

on:
  push:
    tags:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the latest tag
        id: gettag
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Create Deployment Files
        shell: bash
        env:
          LOKI: ${{ secrets.LOKI_URL }}
          CADDY: ${{ secrets.CADDY_FILE }}
          AINV: ${{ secrets.ANSIBLE_INVENTORY }}
          APKEY: ${{ secrets.ANSIBLE_PRIVATE_KEY }}
          NAPIK: ${{ secrets.NOTION_API_KEY }}
          NDID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          echo "$AINV" > ./ansible/inventory.ini
          echo "$APKEY" > ./ansible/key.pem
          echo "$CADDY" > ./ansible/Caddyfile
          chmod 400 ./ansible/key.pem
          sed -i "s#LOKI-REPLACE-ME#$LOKI#g" ./ansible/docker-compose.yml
          sed -i "s#<LATEST_PROD>#${{ github.ref_name }}#g" ./ansible/docker-compose.yml
          sed -i "s#<NDID>#$NDID#g" ./ansible/docker-compose.yml
          sed -i "s#<NAPIK>#$NAPIK#g" ./ansible/docker-compose.yml

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: witnet/website:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64

      - name: Deploy with Ansible
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd ansible
          ansible-galaxy install -r requirements.yml
          export ANSIBLE_CONFIG=./ansible.cfg
          ansible-playbook playbook.yml -vv
